### ISSUE TITLE
Information injection - User Data

### ISSUE THREAD

**Issue by jemacineiras** [ramiletus/fraud-detection#1]
As a Product Owner I want this service to be able to inject/have access to my customers /users data. So it will injest the information from the events generated in my system and store relevant information in the graph database in order to process the queries needed to detect fraud.

Relevant user data will be

- User Id
- User email
- Phone Numbers
-- phone number
-- is principal number
-- Operator

Data should be consumed by the service or injected through a rest call.
May be CQRS pattern will be required.

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-01 |
| Nombre | Se inserta correctamente un Usuario desde el servicio |
| Precondiciones |  1. No existen usuarios en la base de datos |
| Pasos de prueba |  1. Se crea un usuario <br>2. Se establecen unas propiedades arbitrarias para el usuario <br> 3. Se crea un número de teléfono <br> 4. Se establecen unas propiedades arbitrarias para el número de teléfono <br> 5. Se establece el número de teléfono como propiedad del usuario <br> 6. Se guarda el usuario |
| Resultado esperado |  Solo hay un usuario en la base de datos y tiene las propiedades correctas |
| Resultados | El usuario persiste en la base de datos y tiene las propiedades esperadas |
| Aprobado/reprobado | APROBADO |

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-02 |
| Nombre | El servidor responde con un HTTP status code 400 cuando el cuerpo del método POST del endpoint habilitado para registrar usuarios no está bien formado |
| Precondiciones | 1. Un servidor de la aplicación está en marcha |
| Pasos de prueba |  1. Se hace una llamada POST("/users/inject") al servidor con cuerpo inválido, con un correo electrónico mal formado y un campo con valor null |
| Resultado esperado |  El servidor responde con una HTTP response 400, incluido un mensaje con el motivo concreto de la invalidez de la petición |
| Resultados | 400 Bad Request <br>{<br>"phoneNumbers[0].isMainNumber": "no debe ser nulo", <br>"email": "debe ser una dirección de correo electrónico con formato correcto"<br>}
| Aprobado/reprobado |  APROBADO

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-03 |
| Nombre | El servidor responde con un HTTP status code 200 cuando se invoca correctamente el endpoint POST("/users/inject") |
| Precondiciones | 1. Un servidor de la aplicación está en marcha |
| Pasos de prueba | 1. Se hace una llamada POST("/users/inject") al servidor |
| Resultado esperado |  El servidor valida el cuerpo del método POST y responde con una HTTP response 200 |
| Resultados | El servidor responde con un HTTP status code 200
| Aprobado/reprobado | APROBADO
