### ISSUE TITLE
Integrate Customer Events

### ISSUE THREAD

**Issue by jemacineiras** [ramiletus/fraud-detection#11]
As a Product Owner I want a way to integrate Clients events in order to enrich User Data. 
We will need a layer of transformer adapters which will be able to receive events and translate to our domain/logic to complete User Data.

**Comment by ramiletus** [comment]
If I understood correctly, an event streaming technology must be implemented so the clients can use it to insert User Data generation events.

I think Apache Kafka is a good start. It is widely used and Spring has integration with it. I am on it.

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-15 |
| Nombre | El sistema consume eventos de Kafka para la creación de un usuario |
| Precondiciones | - |
| Pasos de prueba |  1. Se produce un mensaje al topic asociado con la información necesaria para crear un usuario (InjectUserCommand.class) 2. El consumidor de la aplicación ejecuta la creación del nuevo usuario |
| Resultado esperado |  El usuario es creado en base de datos |
| Resultados | El usuario es creado en base de datos |
| Aprobado/reprobado |  APROBADO

**Comment by ramiletus** [comment]
After succesfully integrate a Kafka Listener in the application, I have added a RabbitMQ listener and its test.

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-16 |
| Nombre | El sistema consume eventos de RabbitMQ para la creación de un usuario |
| Precondiciones | - |
| Pasos de prueba |  1. Se produce un mensaje en la cola a la que se asocia el listener con la información necesaria para crear un usuario (InjectUserCommand.class) 2. El consumidor de la aplicación ejecuta la creación del nuevo usuario |
| Resultado esperado |  El usuario es creado en base de datos |
| Resultados | El usuario es creado en base de datos |
| Aprobado/reprobado |  APROBADO
