### ISSUE TITLE
Information To Adquire - Devices

### ISSUE THREAD

**Issue by jemacineiras** [ramiletus/fraud-detection#2]
As a Product Owner I want this service to be able to collect device information from the request in order to detect fraud. This information should be linked to the user so we can get how many devices is using an specific user.

Relevant user data will be

- Browser
- Operative system
- ....

Data should be extracted from request headers. The previous list should be completed base on the information we can get from the frontend applications.

**Comment by ramiletus** [comment]
If I understood correctly, the device information must be extracted from the Users' transactions with the webpages of our clients. This is a task that will be done by their frontend applications, so I am going to delegate this extraction to them. I will focus on creating a REST endpoint so device information can be injected through a POST body, with a DTO just like we do in #1 .

I can foresee that the tricky part is going to be on the relation between Device and User, since they are injected in different endpoints. For now, I will make mandatory the inclusion of the User's id in the DTO of the POST endpoint for devices. Like so, a user must be injected before the device they use.

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-04 |
| Nombre | El sistema guarda un Dispositivo y lo relaciona correctamente con el usuario indicado |
| Precondiciones | 1. Un Usuario ha sido creado con anterioridad |
| Pasos de prueba | 1. Se crea un Dispositivo <br> 2. Se establecen unas propiedades arbitrarias y válidas para el Dispositivo <br> 3. Se establece la relación entre Dispositivo y Usuario mediante las propiedades del Usuario <br> 4. Se guarda el Dispositivo |
| Resultado esperado |  El dispositivo persiste en base de datos y está bien relacionado con el Usuario |
| Resultados |  El Usuario tiene una relación con el dispositivo |
| Aprobado/reprobado |  APROBADO |

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-04 |
| Nombre | El sistema guarda un Dispositivo y lo relaciona correctamente con el usuario indicado |
| Precondiciones | 1. Un Usuario ha sido creado con anterioridad |
| Pasos de prueba | 1. Se crea un Dispositivo <br> 2. Se establecen unas propiedades arbitrarias y válidas para el Dispositivo <br> 3. Se establece la relación entre Dispositivo y Usuario mediante las propiedades del Usuario <br> 4. Se guarda el Dispositivo |
| Resultado esperado |  El dispositivo persiste en base de datos y está bien relacionado con el Usuario |
| Resultados |  El Usuario tiene una relación con el dispositivo |
| Aprobado/reprobado |  APROBADO |

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-05 |
| Nombre | El sistema responde con una excepción InstanceNotFoundException cuando el usuario al que se intenta asociar un Dispositivo no existe en la base de datos |
| Precondiciones | - |
| Pasos de prueba | 1. Se crea un Dispositivo <br> 2. Se establecen unas propiedades arbitrarias para el Dispositivo, incluido un userId inexistente <br> 3. Se recupera el Usuario con la id inválida |
| Resultado esperado |  El sistema hace saltar una excepción InstanceNotFoundException |
| Resultados | El sistema hace saltar una excepción InstanceNotFoundException |
| Aprobado/reprobado |  APROBADO |

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-06 |
| Nombre | El servidor responde con un HTTP status code 200 cuando se invoca correctamente el endpoint POST("/devices/inject") |
| Precondiciones | 1. Un servidor de la aplicación está en marcha |
| Pasos de prueba | 1. Se hace una llamada POST("/devices/inject") al servidor |
| Resultado esperado |  El servidor valida el cuerpo del método POST y responde con una HTTP response 200 |
| Resultados | El servidor responde con un HTTP status code 200
| Aprobado/reprobado | APROBADO

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-07 |
| Nombre | El servidor responde con un HTTP status code 400 cuando el cuerpo del método POST del endpoint habilitado para registrar usuarios no está bien formado |
| Precondiciones | 1. Un servidor de la aplicación está en marcha |
| Pasos de prueba |  1. Se hace una llamada POST("/devices/inject") al servidor con cuerpo inválido, con un campo con valor null |
| Resultado esperado |  El servidor responde con una HTTP response 400, incluido un mensaje con el motivo concreto de la invalidez de la petición |
| Resultados | 400 Bad Request <br>{ <br> "browser": "no debe ser nulo" <br>} |
| Aprobado/reprobado |  APROBADO
