### ISSUE TITLE
Fraud detection first query - One User multple Locations - easy solution

### ISSUE THREAD

**Issue by jemacineiras** [ramiletus/fraud-detection#4]
As a Product Owner I want the service to receive a request and be able to defince if looks legit or not base o user data, device and locations.

Since an user can only be in a physical location at a time we need to be able to identify connection apttempts from different devices and locations at the same time. 

This story should provice a solution to that question.
NOTE, take in consideration people can travel so a time window related to an user in several different places in short time window should be allow.

NOTE services like https://opencagedata.com/demo can provide information which need to be store in the graph - locations - in order to query for fraud

**Comment by ramiletus** [comment]
A Transaction object is starting to be needed. This class would represent an interaction of an User with the e-commerce system, and its properties would be the data inserted with the requests that this issue refers to.

Futhermore, I discovered that CYPHER has spatial functions. These could be useful in order to detect the distance between two Locations of several transactions. This distance, divided by difference of the timestamp of the transactions, could give a movement speed for the user. A too high speed could lead us to some impersonation or other kind of fraud.

The CYPHER reference for spatial functions: https://neo4j.com/docs/cypher-manual/current/functions/spatial/

**Comment by ramiletus** [comment]
Another problem related to this issue would be the compatibility of the map reference systems used by the external service ip-api (our provider of IP locations) and CYPHER. As it can be read in the documentation (https://neo4j.com/docs/cypher-manual/current/functions/spatial/) CYPHER uses WGS84, which is the standard for GPS (according to Wikipedia). No information on which system does ip-api use has been found.

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-12 |
| Nombre | El sistema genera satisfactoriamente una Transacción en la base de datos y detecta si es fraude comparando su Localización con la anterior realizada por el mismo Usuario  |
| Precondiciones | 1. Existe un Usuario creado en base de datos. <br> 2. El Usuario creado tiene asociado un Dispositivo en base de datos <br> 3. El Dispositivo creado tiene asociada una Localización en base de datos <br> 4. Se ha establecido una velocidad máxima fija a la que se puede mover un usuario  |
| Pasos de prueba | 1. Se lanza un comando de registro de una Transacción con un userId, un deviceId y un locationId existentes en base de datos <br> 2. Se recuperan el Usuario, el Dispositivo y la Localización correspondientes a las ids <br> 3. Se instancia un objeto Transacción y se relaciona con las entidades obtenidas. <br> 4. Se comprueba si la Transacción es fraude o no, estableciendo su campo isFraud correspondientemente <br> 5. Se guarda la Transacción. 
| Resultado esperado |  El sistema consigue comprobar si la Transacción es fraude y la guarda correctamente en base de datos |
| Resultados | El sistema detecta intentos de fraude correctamente cuando dos transacciones seguidas son muy alejadas en el espacio y la guarda la transacción registrada correctamente en base de datos |
| Aprobado/reprobado |  APROBADO |

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-13 |
| Nombre | El sistema responde con una excepción InstanceNotFoundException cuando el Usuario, el Dispositivo o la Localización a la que se intenta asociar una transacción no existe en la base de datos |
| Precondiciones | - |
| Pasos de prueba | 1. Se lanza un comando de registro de Transacción con un userId, un deviceId y un localizationId inexistentes en base de datos <br> 2. Se recuperan el Usuario, el Dispositivo y la Localización con la ids inválidas |
| Resultado esperado |  El sistema hace saltar una excepción InstanceNotFoundException |
| Resultados | El sistema hace saltar una excepción InstanceNotFoundException |
| Aprobado/reprobado |  APROBADO |

**Comment by ramiletus** [comment]
|   |   |
|---|---|
| Caso de prueba no. | TC-14 |
| Nombre | El servidor responde con un HTTP status code 400 cuando el cuerpo del método POST del endpoint habilitado para registrar transacciones no está bien formado |
| Precondiciones | 1. Un servidor de la aplicación está en marcha |
| Pasos de prueba |  1. Se hace una llamada POST("/transactions/inject") al servidor con cuerpo inválido: un campo con valor null |
| Resultado esperado |  El servidor responde con una HTTP response 400, incluido un mensaje con el motivo concreto de la invalidez de la petición |
| Resultados | 400 Bad Request <br>{ <br> "locationId": "no debe ser nulo" <br>} |
| Aprobado/reprobado |  APROBADO
